# Streamlit secrets configuration
# Copy this file to .streamlit/secrets.toml and add your actual API key

[secrets]
GEMINI_API_KEY = "your_gemini_api_key_here"

# Instructions:
# 1. Get your Gemini API key from: https://makersuite.google.com/app/apikey
# 2. Create a folder called .streamlit in your project directory
# 3. Create a file called secrets.toml in the .streamlit folder
# 4. Copy this content to secrets.toml and replace "your_gemini_api_key_here" with your actual API key
